#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/allwinner/ceres

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a53

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := exdroid
TARGET_NO_BOOTLOADER := true

# Boot Image
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_TAGS_OFFSET := 0xfffffffffff88100
BOARD_RAMDISK_OFFSET := 0x02f88000
BOARD_DTB_OFFSET := 0x03f88000

BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

BOARD_KERNEL_CMDLINE := console=ttyS0,115200 # Minimal
BOARD_KERNEL_CMDLINE += earlyprintk=sunxi-uart,0x05000000
BOARD_KERNEL_CMDLINE += root=/dev/mmcblk0p4 # Minimal
BOARD_KERNEL_CMDLINE += init=/init # Minimal
BOARD_KERNEL_CMDLINE += loglevel=7
BOARD_KERNEL_CMDLINE += androidboot.hardware=sun50iw10p1 # Minimal
BOARD_KERNEL_CMDLINE += androidboot.serialno=5c000c68a3034951e5d
BOARD_KERNEL_CMDLINE += androidboot.boot_type=2
BOARD_KERNEL_CMDLINE += androidboot.mode=normal
BOARD_KERNEL_CMDLINE += androidboot.selinux=permissive # Minimal
BOARD_KERNEL_CMDLINE += firmware_class.path=/vendor/etc/firmware
BOARD_KERNEL_CMDLINE += androidboot.dtbo_idx=0,1,2
BOARD_KERNEL_CMDLINE += car_reverse_config=1
# BOARD_KERNEL_CMDLINE += cma=64M Remove comment when display breaks

BOARD_MKBOOTIMG_ARGS := --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --board ""

BOARD_KERNEL_SEPARATED_DTBO := false
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

# DTBO
BOARD_KERNEL_SEPARATED_DTBO := true

# Kernel
BOARD_KERNEL_IMAGE_NAME := kernel
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_SOURCE := kernel/allwinner/4.9
TARGET_KERNEL_CONFIG := sun50iw10p1_defconfig
TARGET_KERNEL_CLANG_COMPILE := false

# Partitions
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_DTBOIMG_PARTITION_SIZE := 2097152
BOARD_SUPER_PARTITION_SIZE := 2432696320
BOARD_USES_METADATA_PARTITION := true

# Partitions (Dynamic)
BOARD_SUPER_PARTITION_GROUPS := sb
BOARD_SB_PARTITION_LIST := system vendor product
BOARD_SB_SIZE := 2424307712

BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_VENDOR := vendor

# Platform
TARGET_BOARD_PLATFORM := ceres

# Inherit the proprietary files
include vendor/allwinner/ceres/BoardConfigVendor.mk
